-- 1. LOOKUP TABLES
create table countries (
   country_id   number generated by default as identity,
   iso_code     varchar2(3) not null,
   country_name nvarchar2(100) not null,
   constraint pk_countries primary key ( country_id ),
   constraint uq_country_iso unique ( iso_code )
);

create table languages (
   language_id   number generated by default as identity,
   iso_code      varchar2(5) not null,
   language_name nvarchar2(100) not null,
   constraint pk_languages primary key ( language_id ),
   constraint uq_language_iso unique ( iso_code )
);

-- 2. TITLES
create table titles (
   title_id             number generated by default as identity,
   title_name           nvarchar2(300) not null,
   original_language_id number,
   release_date         date,
   runtime_mins         number(4),
   title_type           varchar2(20) not null check ( title_type in ( 'MOVIE',
                                                            'SERIES',
                                                            'EPISODE' ) ),
   description          nclob,
   rating_sum           number default 0,
   rating_count         number default 0,
   avg_rating           number(4,2) default 0,
   poster_path          varchar2(500),
   backdrop_path        varchar2(500),
   trailer_url          varchar2(500),
   status               varchar2(20) check ( status in ( 'Rumored',
                                           'Post Production',
                                           'Released',
                                           'Canceled' ) ),
   budget               number(15),
   revenue              number(15),
   visibility           varchar2(20) default 'PUBLIC' check ( visibility in ( 'PUBLIC',
                                                                    'HIDDEN',
                                                                    'COPYRIGHT_STRIKE',
                                                                    'GEO_BLOCKED' ) ),
   moderation_reason    nvarchar2(500),
   hidden_at            timestamp,
   constraint pk_titles primary key ( title_id ),
   constraint fk_title_lang foreign key ( original_language_id )
      references languages ( language_id )
);

-- 3. SERIES / SEASON / EPISODE
create table series (
   series_id number primary key,
   constraint fk_series_title foreign key ( series_id )
      references titles ( title_id )
         on delete cascade
);

create table seasons (
   season_id     number generated by default as identity,
   series_id     number not null,
   season_number number not null,
   constraint pk_seasons primary key ( season_id ),
   constraint fk_season_series foreign key ( series_id )
      references series ( series_id )
         on delete cascade
);

create table episodes (
   episode_id     number primary key,
   season_id      number not null,
   episode_number number not null,
   air_date       date,
   constraint fk_episode_title foreign key ( episode_id )
      references titles ( title_id )
         on delete cascade,
   constraint fk_episode_season foreign key ( season_id )
      references seasons ( season_id )
         on delete cascade
);

-- 4. STUDIOS
create table studios (
   studio_id   number generated by default as identity,
   studio_name nvarchar2(200) not null,
   country_id  number,
   website_url varchar2(500),
   logo_path   varchar2(500),
   constraint pk_studios primary key ( studio_id ),
   constraint fk_studio_country foreign key ( country_id )
      references countries ( country_id )
);

create table title_studios (
   title_id  number,
   studio_id number,
   constraint pk_title_studios primary key ( title_id,
                                             studio_id ),
   constraint fk_ts_title foreign key ( title_id )
      references titles ( title_id )
         on delete cascade,
   constraint fk_ts_studio foreign key ( studio_id )
      references studios ( studio_id )
         on delete cascade
);

-- 5. PERSONS
create table persons (
   person_id    number generated by default as identity,
   full_name    nvarchar2(200) not null,
   birth_date   date,
   death_date   date,
   gender       varchar2(10) check ( gender in ( 'Male',
                                           'Female',
                                           'Other' ) ),
   country_id   number,
   biography    nclob,
   profile_path varchar2(500),
   constraint pk_persons primary key ( person_id ),
   constraint fk_person_country foreign key ( country_id )
      references countries ( country_id )
);

-- 6. CAST & CREW
create table roles (
   role_id   number generated by default as identity,
   role_name varchar2(50) not null,
   constraint pk_roles primary key ( role_id ),
   constraint uq_role unique ( role_name )
);

create table title_person_roles (
   title_id       number,
   person_id      number,
   role_id        number,
   character_name nvarchar2(200),
   cast_order     number,
   constraint pk_title_person_roles primary key ( title_id,
                                                  person_id,
                                                  role_id ),
   constraint fk_tpr_title foreign key ( title_id )
      references titles ( title_id )
         on delete cascade,
   constraint fk_tpr_person foreign key ( person_id )
      references persons ( person_id )
         on delete cascade,
   constraint fk_tpr_role foreign key ( role_id )
      references roles ( role_id )
);

-- 7. USERS
create table users (
   user_id       number generated by default as identity,
   username      varchar2(50) not null,
   email         varchar2(255) not null,
   password_hash varchar2(512) not null,
   role          varchar2(20) default 'USER' check ( role in ( 'USER',
                                                      'MODERATOR',
                                                      'ADMIN' ) ),
   is_active     number(1) default 1,
   created_at    timestamp default current_timestamp,
   constraint pk_users primary key ( user_id ),
   constraint uq_username unique ( username ),
   constraint uq_email unique ( email )
);

-- 8. REVIEWS
create table reviews (
   review_id     number generated by default as identity,
   title_id      number not null,
   user_id       number not null,
   rating        number(2) check ( rating between 1 and 10 ),
   review_text   nclob,
   created_at    timestamp default current_timestamp,
   helpful_votes number default 0,
   has_spoilers  number(1) default 0,
   constraint pk_reviews primary key ( review_id ),
   constraint fk_review_title foreign key ( title_id )
      references titles ( title_id )
         on delete cascade,
   constraint fk_review_user foreign key ( user_id )
      references users ( user_id )
         on delete cascade,
   constraint uq_user_title unique ( title_id,
                                     user_id )
);

-- 9. AUDIT LOG
create sequence imdb_admin.seq_audit_log start with 1 increment by 1;

create table imdb_admin.title_audit_log (
   log_id      number default imdb_admin.seq_audit_log.nextval primary key,
   title_id    number,
   action_type varchar2(20) check ( action_type in ( 'INSERT',
                                                     'UPDATE',
                                                     'DELETE' ) ),
   old_title   nvarchar2(300),
   new_title   nvarchar2(300),
   action_date timestamp default current_timestamp,
   action_user varchar2(50)
);

-- 10. INDEXES
create index imdb_admin.idx_titles_name on
   imdb_admin.titles (
      title_name
   );
create index imdb_admin.idx_titles_release on
   imdb_admin.titles (
      release_date
   );
create index imdb_admin.idx_titles_rating on
   imdb_admin.titles (
      avg_rating
   );
create index imdb_admin.idx_persons_name on
   imdb_admin.persons (
      full_name
   );
create index imdb_admin.idx_reviews_title on
   imdb_admin.reviews (
      title_id
   );
create index imdb_admin.idx_reviews_user on
   imdb_admin.reviews (
      user_id
   );
create index imdb_admin.idx_tpr_title on
   imdb_admin.title_person_roles (
      title_id
   );
create index imdb_admin.idx_tpr_person on
   imdb_admin.title_person_roles (
      person_id
   );
create index imdb_admin.idx_tpr_role on
   imdb_admin.title_person_roles (
      role_id
   );
create index imdb_admin.idx_title_studio_title on
   imdb_admin.title_studios (
      title_id
   );
create index imdb_admin.idx_title_studio_studio on
   imdb_admin.title_studios (
      studio_id
   );
create index imdb_admin.idx_season_series on
   imdb_admin.seasons (
      series_id
   );
create index imdb_admin.idx_episode_season on
   imdb_admin.episodes (
      season_id
   );

-- 11. VIEWS
create or replace view imdb_admin.vw_title_details as
   select t.title_id,
          t.title_name,
          t.title_type,
          t.release_date,
          t.runtime_mins,
          t.avg_rating,
          t.rating_count,
          l.language_name
     from imdb_admin.titles t
     left join imdb_admin.languages l
   on t.original_language_id = l.language_id;

create or replace view imdb_admin.vw_user_reviews as
   select r.review_id,
          u.username,
          t.title_name,
          r.rating,
          r.review_text,
          r.created_at
     from imdb_admin.reviews r
     join imdb_admin.users u
   on r.user_id = u.user_id
     join imdb_admin.titles t
   on r.title_id = t.title_id;

-- 12. TRIGGERS
create or replace trigger imdb_admin.trg_update_title_rating after
   insert or update or delete on imdb_admin.reviews
   for each row
begin
   if inserting then
      update imdb_admin.titles
         set rating_sum = rating_sum + :new.rating,
             rating_count = rating_count + 1,
             avg_rating = ( rating_sum + :new.rating ) / ( rating_count + 1 )
       where title_id = :new.title_id;
   elsif deleting then
      update imdb_admin.titles
         set rating_sum = rating_sum - :old.rating,
             rating_count = rating_count - 1,
             avg_rating =
                case
                   when ( rating_count - 1 ) <= 0 then
                      0
                   else
                      ( rating_sum - :old.rating ) / ( rating_count - 1 )
                end
       where title_id = :old.title_id;
   elsif updating then
      update imdb_admin.titles
         set rating_sum = rating_sum - :old.rating + :new.rating,
             avg_rating = ( rating_sum - :old.rating + :new.rating ) / nullif(
                rating_count,
                0
             )
       where title_id = :new.title_id;
   end if;
end;
/

create or replace trigger imdb_admin.trg_audit_title_changes after
   insert or update or delete on imdb_admin.titles
   for each row
declare
   v_action varchar2(20);
   v_user   varchar2(50);
begin
   select user
     into v_user
     from dual;

   if inserting then
      v_action := 'INSERT';
      insert into imdb_admin.title_audit_log (
         title_id,
         action_type,
         new_title,
         action_user
      ) values ( :new.title_id,
                 v_action,
                 :new.title_name,
                 v_user );
   elsif updating then
      v_action := 'UPDATE';
      insert into imdb_admin.title_audit_log (
         title_id,
         action_type,
         old_title,
         new_title,
         action_user
      ) values ( :new.title_id,
                 v_action,
                 :old.title_name,
                 :new.title_name,
                 v_user );
   elsif deleting then
      v_action := 'DELETE';
      insert into imdb_admin.title_audit_log (
         title_id,
         action_type,
         old_title,
         action_user
      ) values ( :old.title_id,
                 v_action,
                 :old.title_name,
                 v_user );
   end if;
end;
/

-- 13. PACKAGES
create or replace package imdb_admin.pkg_title_management as
   function fn_get_total_reviews (
      p_title_id in number
   ) return number;
   procedure prc_add_title (
      p_title_name   in varchar2,
      p_release_date in date,
      p_runtime      in number,
      p_title_type   in varchar2,
      p_language_id  in number,
      p_title_id     out number
   );
   procedure prc_add_review (
      p_title_id    in number,
      p_user_id     in number,
      p_rating      in number,
      p_review_text in clob
   );
end pkg_title_management;
/

create or replace package body imdb_admin.pkg_title_management as
   function fn_get_total_reviews (
      p_title_id in number
   ) return number is
      v_total number := 0;
   begin
      select rating_count
        into v_total
        from imdb_admin.titles
       where title_id = p_title_id;
      return v_total;
   exception
      when no_data_found then
         return 0;
      when others then
         return -1;
   end fn_get_total_reviews;

   procedure prc_add_title (
      p_title_name   in varchar2,
      p_release_date in date,
      p_runtime      in number,
      p_title_type   in varchar2,
      p_language_id  in number,
      p_title_id     out number
   ) is
   begin
      insert into imdb_admin.titles (
         title_name,
         release_date,
         runtime_mins,
         title_type,
         original_language_id,
         status,
         visibility
      ) values ( p_title_name,
                 p_release_date,
                 p_runtime,
                 p_title_type,
                 p_language_id,
                 'Released',
                 'PUBLIC' ) returning title_id into p_title_id;
      commit;
   exception
      when others then
         rollback;
         raise;
   end prc_add_title;

   procedure prc_add_review (
      p_title_id    in number,
      p_user_id     in number,
      p_rating      in number,
      p_review_text in clob
   ) is
   begin
      if p_rating < 1
      or p_rating > 10 then
         raise_application_error(
            -20001,
            'Điểm đánh giá phải từ 1 đến 10.'
         );
      end if;

      insert into imdb_admin.reviews (
         title_id,
         user_id,
         rating,
         review_text
      ) values ( p_title_id,
                 p_user_id,
                 p_rating,
                 p_review_text );
      commit;
   exception
      when dup_val_on_index then
         rollback;
         raise_application_error(
            -20002,
            'User đã review title này rồi.'
         );
      when others then
         rollback;
         raise;
   end prc_add_review;
end pkg_title_management;
/

-- 14. SAMPLE DATA
insert into imdb_admin.countries (
   iso_code,
   country_name
) values ( 'US',
           'United States' );
insert into imdb_admin.languages (
   iso_code,
   language_name
) values ( 'en',
           'English' );
insert into imdb_admin.studios (
   studio_name,
   country_id
) values ( 'Warner Bros.',
           1 );
insert into imdb_admin.roles ( role_name ) values ( 'Director' );
insert into imdb_admin.roles ( role_name ) values ( 'Actor' );
insert into imdb_admin.persons (
   full_name,
   birth_date,
   country_id
) values ( 'Christopher Nolan',
           to_date('1970-07-30','YYYY-MM-DD'),
           1 );
insert into imdb_admin.persons (
   full_name,
   birth_date,
   country_id
) values ( 'Christian Bale',
           to_date('1974-01-30','YYYY-MM-DD'),
           1 );
insert into imdb_admin.titles (
   title_name,
   release_date,
   runtime_mins,
   title_type,
   original_language_id,
   status
) values ( 'The Dark Knight',
           to_date('2008-07-18','YYYY-MM-DD'),
           152,
           'MOVIE',
           1,
           'Released' );
insert into imdb_admin.title_studios (
   title_id,
   studio_id
) values ( 1,
           1 );
insert into imdb_admin.title_person_roles (
   title_id,
   person_id,
   role_id,
   character_name,
   cast_order
) values ( 1,
           1,
           1,
           null,
           0 );
insert into imdb_admin.title_person_roles (
   title_id,
   person_id,
   role_id,
   character_name,
   cast_order
) values ( 1,
           2,
           2,
           'Bruce Wayne / Batman',
           1 );
insert into imdb_admin.users (
   username,
   email,
   password_hash
) values ( 'john_doe',
           'john@example.com',
           'hash123' );
commit;

-- 15. ROLES & USERS
create role role_content_manager;
grant select,insert,update,delete on imdb_admin.titles to role_content_manager;
grant select,insert,update,delete on imdb_admin.studios to role_content_manager;
grant select,insert,update,delete on imdb_admin.persons to role_content_manager;
grant select,insert,update,delete on imdb_admin.roles to role_content_manager;
grant select,insert,update,delete on imdb_admin.title_person_roles to role_content_manager;
grant select,insert,update,delete on imdb_admin.title_studios to role_content_manager;
grant select,insert,update,delete on imdb_admin.title_audit_log to role_content_manager;
grant execute on imdb_admin.pkg_title_management to role_content_manager;

create role role_viewer;
grant select on imdb_admin.vw_title_details to role_viewer;
grant select on imdb_admin.vw_user_reviews to role_viewer;
grant select on imdb_admin.titles to role_viewer;
grant select on imdb_admin.reviews to role_viewer;
grant insert,update on imdb_admin.reviews to role_viewer;
grant execute on imdb_admin.pkg_title_management to role_viewer;

alter session set "_ORACLE_SCRIPT" = true;

create user viewer_01 identified by 123456;
grant create session to viewer_01;
grant role_viewer to viewer_01;

create user content_mgr_01 identified by 123456;
grant create session to content_mgr_01;
grant role_content_manager to content_mgr_01;

-- 16. TEST SCRIPTS
   SET SERVEROUTPUT ON;
declare
   v_new_title_id number;
begin
   imdb_admin.pkg_title_management.prc_add_title(
      p_title_name   => 'Inception',
      p_release_date => to_date('2010-07-16',
                                   'YYYY-MM-DD'),
      p_runtime      => 148,
      p_title_type   => 'MOVIE',
      p_language_id  => 1,
      p_title_id     => v_new_title_id
   );
   dbms_output.put_line('Thêm tác phẩm thành công. ID mới: ' || v_new_title_id);
   imdb_admin.pkg_title_management.prc_add_review(
      p_title_id    => v_new_title_id,
      p_user_id     => 1,
      p_rating      => 9,
      p_review_text => 'Một siêu phẩm hack não!'
   );
   dbms_output.put_line('Thêm đánh giá thành công! Trigger O(1) đã tự động tính toán điểm.');
   begin
      imdb_admin.pkg_title_management.prc_add_review(
         p_title_id    => v_new_title_id,
         p_user_id     => 1,
         p_rating      => 15,
         p_review_text => 'Phim quá hay cho hẳn 15 điểm!'
      );
   exception
      when others then
         dbms_output.put_line('Đã bắt được ngoại lệ nghiệp vụ (Sai điểm): ' || sqlerrm);
   end;
end;
/

   SET SERVEROUTPUT ON;
declare
   v_title_id number := 1;
   v_user_id  number := 1;
begin
   begin
      imdb_admin.pkg_title_management.prc_add_review(
         p_title_id    => v_title_id,
         p_user_id     => v_user_id,
         p_rating      => 9,
         p_review_text => 'Phim rất hay!'
      );
      dbms_output.put_line('Lần 1: Thêm đánh giá thành công.');
   exception
      when others then
         dbms_output.put_line('Lần 1 có lỗi (Có thể đã review trước đó): ' || sqlerrm);
   end;

   begin
      imdb_admin.pkg_title_management.prc_add_review(
         p_title_id    => v_title_id,
         p_user_id     => v_user_id,
         p_rating      => 8,
         p_review_text => 'Tôi muốn đổi điểm số.'
      );
      dbms_output.put_line('Lần 2: Thêm đánh giá thành công (Lỗi! Đáng lẽ phải thất bại).');
   exception
      when others then
         dbms_output.put_line('Lần 2 bắt được lỗi Unique đúng như thiết kế: ' || sqlerrm);
   end;
end;
/

update imdb_admin.titles
   set
   title_name = 'The Dark Knight (Remastered)'
 where title_id = 1;
commit;

select log_id,
       title_id,
       action_type,
       old_title,
       new_title,
       action_user,
       action_date
  from imdb_admin.title_audit_log
 where title_id = 1
 order by action_date desc;